services:
  - type: web
    name: django-todo
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn yourprojectname.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString

databases:
  - name: your-db-name
    plan: free
